---
title: "Plots"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(here::here(), "docs", "plots_report")) })
output: 
  pdf_document:
    keep_tex: true
fontsize: 12pt
header-includes:
  - |
    ```{=latex}
    \usepackage{booktabs}	
    ```
---

```{r install-packages, eval = FALSE, include = FALSE}
install.packages("orderly", repos = "http://cran.us.r-project.org")
install.packages("knitr", repos = "http://cran.us.r-project.org")
install.packages("here", repos = "http://cran.us.r-project.org")
install.packages("tidyr", repos = "http://cran.us.r-project.org")
install.packages("plyr", repos = "http://cran.us.r-project.org")
install.packages("dplyr", repos = "http://cran.us.r-project.org")
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
install.packages("scales", repos = "http://cran.us.r-project.org")
install.packages("ggpubr", repos = "http://cran.us.r-project.org")
install.packages("kableExtra", repos = "http://cran.us.r-project.org")
install.packages("systemfonts", repos = "http://cran.us.r-project.org")
install.packages("svglite", repos = "http://cran.us.r-project.org")
```

```{r load-packages, include=FALSE}
library(tidyr)
library(orderly)
library(here)
library(plyr)
library(dplyr)
library(ggplot2)
library(scales)
library(ggpubr)
library(kableExtra)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r get-paths}
stage = "generate_production_counterfactual"
id = orderly::orderly_latest(stage)
prod_cfact_path = paste0("../archive/", stage, "/", id)

stage = "generate_vaccine_counterfactual"
id = orderly::orderly_latest(stage)
vacc_cfact_path = paste0("../archive/", stage, "/", id)

stage = "generate_counterfactuals"
id = orderly::orderly_latest(stage)
cfacts_path = paste0("../archive/", stage, "/", id)

stage = "deaths_averted_plot_timeline"
id = orderly::orderly_latest(stage)
deaths_av_path = paste0("../archive/", stage, "/", id)
```

```{r set-theme}
fontsize = 12

colour_direct <- "#98df8a"
colour_total <- "#17becf"
colour_baseline <- "black"
colour_counterfactual <- "#d62728"

theme = theme_bw() +
  theme(text = element_text(family = "serif", size = fontsize),
        legend.position = 'bottom')
theme_set(theme)
```

```{r cumul-vacc-cfacts, fig.align="center", fig.cap=c("DJ4 Cumulative vaccine counterfactuals")}
baseline = readRDS(paste0(vacc_cfact_path, "/counterfactual_timelines/owid_raw.Rds"))
sooner_30 = readRDS(paste0(vacc_cfact_path, "/counterfactual_timelines/30_days_sooner.Rds"))
sooner_60 = readRDS(paste0(vacc_cfact_path, "/counterfactual_timelines/60_days_sooner.Rds"))
sooner_90 = readRDS(paste0(vacc_cfact_path, "/counterfactual_timelines/90_days_sooner.Rds"))

counterfactuals = bind_rows(baseline, sooner_30, sooner_60, sooner_90)

dj4 = ggplot() +
  geom_line(data = counterfactuals,
            aes(x = as.Date(date),
                y = total_vacc,
                color = shifted_by)) +
  facet_wrap(~country, ncol = 2, scales = "free_y") +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
  scale_colour_manual(
    labels = c('30 days', '60 days', '90 days', 'baseline'),
    values = c(alpha(colour_counterfactual, 0.33), alpha(colour_counterfactual, 0.66), colour_counterfactual, colour_baseline)
  ) +
  labs(x = "Date",
       y = "Cumulative vaccinations",
       color = "Vaccinations starting sooner by:")

plot(dj4)
```
```{r vaccinations-table}
vaccinations_table = counterfactuals %>%
  filter(date %in% c(
    as.Date('2021-01-01'),
    as.Date('2021-04-01'),
    as.Date('2021-07-01')
  )) %>%
  select(country, date, total_vacc, shifted_by) %>%
  mutate(
    total_vacc = format(total_vacc,
                        big.mark = ",",
                        trim = TRUE),
    shifted_by = mapvalues(
      shifted_by,
      from = c("baseline", "30", "60", "90"),
      to = c(
        "Baseline",
        "Vaccines 30 days sooner",
        "Vaccines 60 days sooner",
        "Vaccines 90 days sooner"
      )
    )
  ) %>%
  rename(
    c(
      "Counterfactual scenario" = "shifted_by"
    )
  ) %>%
  pivot_wider(names_from = date,
              values_from = total_vacc) %>%
  replace(is.na(.), '0') %>%
  arrange(country) %>%
  select(-country)

vaccinations_table %>%
  kbl(booktabs=TRUE, centering = TRUE, caption = "Total vaccinations at sample dates") %>%
  pack_rows("United Kingdom", 1, 4) %>%
  pack_rows("United States", 5, 8)

```


```{r deaths-averted-table}
cfacts_to_display = c("30_days_sooner",
                     "60_days_sooner",
                     "90_days_sooner")
labels_to_display = c("Vaccines 30 days sooner",
                     "Vaccines 60 days sooner",
                     "Vaccines 90 days sooner")

deaths_averted_summary = readRDS(paste0(deaths_av_path, "/deaths_averted_summary.Rds"))

# source: https://data.worldbank.org/indicator/SP.POP.TOTL
population = data.frame(
  iso3c = c("GBR", "USA"),
  pop10k = c(67081000, 331501080) / 10000
)

with_pop = deaths_averted_summary %>%
  left_join(population, by = "iso3c") %>%
  mutate(averted_deaths_perpop_avg = averted_deaths_avg / pop10k,
         averted_deaths_perpop_025 = averted_deaths_025 / pop10k,
         averted_deaths_perpop_975 = averted_deaths_975 / pop10k)

differences_table = with_pop %>%
  filter(counterfactual %in% cfacts_to_display) %>%
  mutate(
    delta_deaths = paste0(
      format(
        round(averted_deaths_avg, 0),
        big.mark = ",",
        trim = TRUE
      ),
      " [",
      format(
        round(averted_deaths_025, 0),
        big.mark = ",",
        trim = TRUE
      ),
      "; ",
      format(
        round(averted_deaths_975, 0),
        big.mark = ",",
        trim = TRUE
      ),
      "]"
    ),
    delta_deaths_perpop = paste0(
      format(
        round(averted_deaths_perpop_avg, 2),
        big.mark = ",",
        trim = TRUE
      ),
      " [",
      format(
        round(averted_deaths_perpop_025, 2),
        big.mark = ",",
        trim = TRUE
      ),
      "; ",
      format(
        round(averted_deaths_perpop_975, 2),
        big.mark = ",",
        trim = TRUE
      ),
      "]"
    ),
    counterfactual_label = mapvalues(counterfactual,
                                     from = cfacts_to_display,
                                     to = labels_to_display),
    iso3c = as.factor(iso3c)
  ) %>%
  mutate(counterfactual_label = factor(counterfactual_label,
                                       labels_to_display)) %>%
  arrange(iso3c, counterfactual_label) %>%
  select(counterfactual_label,
         delta_deaths,
         delta_deaths_perpop,) %>%
  rename(
    c(
      "Counterfactual scenario" = "counterfactual_label",
      "Deaths averted" = "delta_deaths",
      "Deaths averted per 10,000" = "delta_deaths_perpop"
    )
  )

differences_table %>%
  kbl(booktabs=TRUE, centering = TRUE, caption = "DJ5 Averted deaths") %>%
  pack_rows("United Kingdom", 1, 3) %>%
  pack_rows("United States", 4, 6)

```

```{r deaths-averted-plot, fig.align="center", fig.cap=c("DJ6 Daily deaths per scenario")}
deaths_averted = readRDS(paste0(deaths_av_path, "/deaths_averted_detail.Rds"))

zoomed_deaths_averted = deaths_averted %>%
  filter(date > as.Date("2020-09-01")) %>%
  filter(counterfactual %in% cfacts_to_display) %>%
  mutate(counterfactual_label = mapvalues(
    counterfactual,
    from = cfacts_to_display,
    to = labels_to_display
  )) %>%
  mutate(counterfactual_label = factor(counterfactual_label,
                                       labels_to_display))

single_timeseries_plot = ggplot(zoomed_deaths_averted, aes(x = date)) +
  geom_line(aes(y = baseline_deaths_avg, colour = "baseline")) +
  geom_line(aes(y = deaths_avg, colour = "counterfactual")) +
  geom_ribbon(
    aes(ymin = deaths_025, ymax = deaths_975),
    alpha = 0.3,
    fill = colour_counterfactual
  ) +
  facet_grid(counterfactual_label ~ country,
             labeller = labeller(.rows=label_wrap_gen(width = 15))) +
  scale_colour_manual(
    labels = c('baseline', 'counterfactual'),
    values = c(colour_baseline, colour_counterfactual)
  ) +
  labs(x = "Date", y = "Daily Deaths", color = "Colour")
  

plot(single_timeseries_plot)


```

```{r prod-assumptions, fig.align="center", fig.cap=c("DJ9 Vaccine production assumptions")}
detail_prod = readRDS(paste0(prod_cfact_path, "/detail_production.Rds"))
pfizer_prod = readRDS(paste0(prod_cfact_path, "/pfizer_estimated_production.Rds"))
moderna_prod = readRDS(paste0(prod_cfact_path, "/moderna_estimated_production.Rds"))

plot1 = ggplot() +
  geom_line(data = detail_prod,
            aes(x = date, y = cumulative_available_vaccines)) +
  xlab("Date") +
  ylab("Cumulative vaccines available") +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))

plot2 = ggplot() +
  geom_line(data = detail_prod,
            aes(x = date, y = daily_vaccines)) +
  xlab("Date") +
  ylab("Daily vaccines produced") +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))

plot3 = ggplot() +
  geom_line(data = moderna_prod,
            aes(x = date, y = daily_production)) +
  xlab("Date") +
  ylab("Daily vaccines produced\nModerna") +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))

plot4 = ggplot() +
  geom_line(data = pfizer_prod,
            aes(x = date, y = daily_production)) +
  xlab("Date") +
  ylab("Daily vaccines produced\nPfizer") +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))

combined_plot =
  ggarrange(plot3,
            plot4,
            plot2,
            plot1,
            nrow = 2,
            ncol = 2)
plot(combined_plot)
```

```{r prod-cap, fig.align="center", fig.cap=c("DJ10 Limits from production")}
production = readRDS(paste0(prod_cfact_path, "/counterfactual_production.Rds"))

countries_of_interest = c("United States", "United Kingdom")
for (country_name in countries_of_interest) {
  country_cfact = counterfactuals %>%
    filter(country == country_name) %>%
    mutate(shifted_by = factor(
      shifted_by,
      levels = c("baseline", "30", "60", "90"),
      labels = c(
        "Baseline",
        "Vaccines 30 days sooner",
        "Vaccines 60 days sooner",
        "Vaccines 90 days sooner"
      )
    ))
    country_prod = production %>% filter(country == country_name)
    
  
  dj10 = ggplot() +
    geom_line(data = country_prod,
              aes(
                x = as.Date(date),
                y = cumulative_available_vaccines,
                color = "Production"
              )) +
    geom_line(data = country_cfact,
              aes(
                x = as.Date(date),
                y = total_vacc,
                color = "Vaccination"
              )) +
    labs(x = "Date",
         y = "Cumulative production / vaccinations",
         color = "Colour") +
    ggtitle(country_name) +
    scale_colour_manual(
      labels = c('Production', 'Vaccination'),
      values = c(colour_baseline, colour_counterfactual)
    ) +
    scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
    facet_wrap(~ shifted_by)
  
  plot(dj10)
}
```

