\newpage
# Introduction

The development and testing of vaccines for COVID-19 progressed at an unprecedented pace, with vaccinations approved in some countries within less than a year from the start of the pandemic. However, even with accelerated approvals the COVID-19 pandemic had a devastating impact on global health and economies. In the United States and United Kingdom alone, hundreds of thousands of lives were lost in the period it took to approve and complete mass vaccinations.

It has been suggested that various interventions could have led to the vaccines becoming available even earlier. For example, in the United States some have pointed out that while the clinical trials were conducted efficiently, the emergency use authorization process still involved a gap of several weeks between completing phase 3 studies and the start of mass vaccination. Also in the US, others argued that vaccines should have been approved earlier based on the FDA’s “animal rule” and compassionate use pathways for certain groups.[^1] Another proposal to accelerate vaccine availability involved use of human challenge trials (HCTs) to speed up generation of vaccine efficacy results.[^2] 

Abstracting from the particular way that vaccines might have been made available earlier and feasibility or risks of any of the possible approaches, it is pertinent to ask what the possible health benefits of such an approach would have been. A priori both health and economic benefits seem likely to be significant. For example, economic research into accelerating COVID vaccine availability has suggested that these benefits may be orders of magnitude larger than the costs associated with acceleration [@Castillo2021Market]. 

Despite this, there has been relatively little research on the impact of speed on health benefits, particularly in terms of earlier approval and by using epidemiological modelling. A recent review paper found only one such quantitative estimate for mortality [@Wiecek2022Clinical]. This estimate, from @Berry2020ACost, was based on prospective simulation done early in the pandemic, which understandably overestimated timelines for vaccine field trials and was not able to use information about time-course of the COVID-19 pandemic in 2020 and 2021 to calibrate the model.[^3] 

In this paper, we aim to provide a simple revision to this approach, where we use retrospective data to quantify the potential health benefits (which we measure in terms of deaths averted) of accelerating the availability of COVID-19 vaccines. More concretely, we proceed in two stages. First, we calibrate an epidemiological model informed by retrospective analysis of data on observed vaccinations and mortality. Then, considering the actual vaccine development and approval timelines and comparing them to counterfactual acceleration scenarios, we simulate counterfactual epidemics and their associated mortality. 

It is important to note that we consider hypothetical accelerated timelines, rather than evaluating risk-benefits from implementing concrete innovations which in some cases may trade off risk (less precise information on efficacy or safety) for speed. We are interested only in the magnitude of potential benefits. For this reason, we do not consider health risks to the general population that accelerating approval of less effective or safe vaccines would result in [@Chandra2022Regulatory].

We calculate the health benefits for two countries only, the United States and the United Kingdom.[^4] They are large developed countries that were at the front of the queue for vaccine deliveries and therefore would have been among those most likely to benefit from accelerated testing. However, there are also considerable differences in timing of waves, circulating variants, speed of vaccination, adoption of boosters, and vaccine prioritisation, to name a few. Therefore it’s instructive to compare the two cases. As we will discuss throughout this article, we contrast these two countries to provide an illustrative example, because they differed in the nature of epidemics (timing of waves, different strains), non-pharmaceutical interventions, and vaccination policy and uptake.

Our epidemiological modelling approach simplifies many relevant real-world factors, including individual behaviours and responses to public health interventions. Therefore, we also conduct some sensitivity analyses and discuss some potential unknowns associated with accelerating vaccine approvals, such as (1) less precise information on efficacy or safety, (2) impact on public confidence in vaccines, (3) the potential for production and distribution constraints to nullify the benefits of accelerated testing.

[^1]: In the US, in situations in which human clinical trial testing may not be feasible or unethical, animal trials may be used in place of clinical trials (referred to as the “animal rule”) or patients who have sufficient need for a possible therapy (such as terminally ill patients) so as to forgo possible safety or efficacy concerns may receive experimental drugs (referred to as “compassionate use”) [@Commissioner2023Animal, @Rizk2021Expanded]. However, the obvious deficit of these approaches is that they are not based on much weaker efficacy and safety data than a EUA pathway.

[^2]: In HCTs a small group of volunteers are intentionally infected with a disease in order to study the efficacy of potential treatments or vaccines. While both ethical and technological barriers to adoption of HCTs are considerable (as we will discuss in more detail later), they have the potential to significantly accelerate the efficacy studies, at least in theory.

[^3]: We discuss other estimates of benefits of speed at the end of the paper.

[^4]: The model we use could also estimate reductions in infections. Similarly, we could estimate reductions in hospitalisations or severe cases. However, for simplicity we focus only on mortality, since the relative reductions in all outcomes can be thought of as roughly comparable, and averting deaths is typically the main variable that is of interest to public health decision makers.


