```{r lives-saved-data, echo=FALSE}
differences_table <- load_deaths_averted_table( excess = FALSE) %>% 
  filter(date == "2021-07-01") %>% 
  select(iso3c, counterfactual, cumulative_averted_deaths_avg) 

saved30 = differences_table %>% filter(counterfactual == "30_days_sooner") %>% 
  summarize(averted_deaths = -sum(cumulative_averted_deaths_avg)) %>% 
  pull(averted_deaths)
saved60 = differences_table %>% filter(counterfactual == "60_days_sooner") %>% 
  summarize(averted_deaths = -sum(cumulative_averted_deaths_avg)) %>% 
  pull(averted_deaths)
saved90 = differences_table %>% filter(counterfactual == "90_days_sooner") %>% 
  summarize(averted_deaths = -sum(cumulative_averted_deaths_avg)) %>% 
  pull(averted_deaths)

success_probability = 0.33

expected_lives_saved = success_probability*(0.06*saved30 + 0.03*saved60 + 0.01*saved90)
expected_lives_saved_formatted = format(signif(expected_lives_saved, 2), big.mark = ",", scientific = FALSE)

cost_per_life <- 1e06 / expected_lives_saved
cost_per_life_fmt <- format(signif(cost_per_life, 2), big.mark = ",", scientific = FALSE)
```

# Discussion

Overall, using an epidemiological model we find large health benefits from accelerating availability of vaccines, both in the UK and the US. In our main period of interest, from the start of vaccination up to 1 July 2021, these reductions range on average from 1.4 up to 7.1 lives saved per 10,000 people, depending on country and amount of acceleration of vaccination schedule (30-90 days). These are obviously large numbers, corresponding to 63,000-180,000 lives saved in two countries alone in the modeled period.[^17] 

However, our results are uncertain and sensitive to choice of the model, as is typical in all such epidemiological modelling studies. Each counterfactual calculation of deaths averted (see Table \@ref(tab:deaths-averted-table)) varied highly, depending on vaccine parameters. Moreover, there are several sources of uncertainty not captured by the 95% intervals we cite. First, as our sensitivity analyses show, model misspecification would have considerable impact on the estimates of deaths averted. Second, the benefits are sensitive to the choice of whether we model reductions in excess deaths or confirmed deaths. Third, relative reductions in mortality depend on the time horizon of the analysis, since in some cases reductions in mortality from the initial wave are balanced by increase in cases in later waves. 

In sum, while our results should be seen as indicative of large potential gains, they should not be treated as precise estimates. However, the variability in results underscores how benefits of mass vaccination are highly sensitive to their timing before epidemic waves and the crucial role of sustaining protection during subsequent waves, to avoid a rebound in cases. The difficulty of estimating potential mortality reductions related to the fact that duration of vaccine-induced and natural protection (which drive the rebound) are hard to estimate even retrospectively.

We are not aware of retrospective epidemiological analyses of how mortality changes with earlier start of mass vaccinations, but our overall conclusion of possible large gains from accelerating availability of vaccines fits into a growing literature on benefits of accelerating vaccination. For example, @Bjoerkheim2022COVID estimate 40,000 lives in the US could have been saved by making vaccines available 3 months earlier to care home residents. However, their model is not epidemiological and restricted to a particular population. A recent modelling work by @Imai2023Quantifying, also using retrospective data, suggests that extending interval between doses in the UK (from a 3-week gap to 12 weeks) averted 10,000 deaths in the period up to September 2021, an about 16% decrease in mortality. Many simulations (see, for example, @Bubar2021Model) predict large differences in benefits depending on prioritization strategies when vaccine supply is constrained, especially with regards to age. Another epidemiological simulation suggests that 22-47% of deaths could have been averted in COVID waves if the speed of vaccinations was doubled, with significant gains possible even if a less effective vaccine was used, for example via fractional dosing [@Wiecek2022Testing].


## Do benefits justify investment?

Does the large health benefit found by our model justify investing more into additional trials? Consider the following illustrative example. Firstly, let's assume that going into Phase II COVID vaccine developers predicted a 33% chance of success.[^18] Secondly, let’s assume some hypothetical innovation (faster field trials, use of HCTs, streamlined approval process) has a 6% chance of accelerating approval by 30 days, 3% by 60 days or 1% by 90 days. In expectation this gives `r expected_lives_saved_formatted` lives saved in two countries. If implementing this innovation for all leading vaccine candidates cost 100 million USD total, that's still about `r cost_per_life_fmt` USD per life saved. This figure ignores other health and economic benefits and the fact that a vaccine is a global public good. If we were to factor these in, the benefits would have likely been even orders of magnitude larger.

The 100 million cost quoted here is just a rough estimate. Costs will of course depend on the type of innovation used to accelerate the trial. In the UK, the world's first coronavirus human challenge study, conducted by hVIVO, which involved up to 90 volunteers, was backed by a £33.6 million UK government investment.[^19] In a pandemic setting these costs will be likely higher, e.g. overall funding for vaccine R&D in the US provided by the government amounted to $1.7 billion, but only part of it was spent on clinical trials [@Lalani2023US]. Moreover, the probabilities of acceleration that we assumed in the above example (6%, 3%, and 1%) are purely hypothetical. 

We focus on two illustrative cases, of the UK and the US. Implicit in our approach is the assumption of the first mover advantage, i.e. that the benefits of speed accrue most in countries that can accelerate regulatory approval the most. For that reason, countries with smaller populations also stand to gain more. For larger countries it’s more likely that the manufacturing constraints will bind them, preventing them from reaping all benefits of accelerating vaccine approvals early on.


## Considerations for HCTs of vaccine efficacy

Many of the debates about speeding up vaccine testing have focused on using HCTs to determine efficacy. While our results suggest large benefits of even those clinical trial innovations that have relatively small probability to accelerate approval, it is important to note that there is currently no clear regulatory framework for the use of human challenge trials for vaccine evaluation or licensure (see @Baylor2021Human). Establishing a regulatory framework in advance of a pandemic would be key to capitalizing on any possible benefits of human challenge trials, in particular, building consensus on how human challenge trials can be used for facilitating emergency use authorization for a vaccine. 

As with any clinical trial, human challenge studies are not without risks, and require a number of ethical considerations. This is especially the case when conducting challenge studies with pandemic pathogens, where the administered pathogen is especially virulent or deadly, without available therapeutics. As such ensuring robust safety measures are in place to protect patient safety is paramount.[^20] These might include robust informed consent processes, ethical assessments by external review boards, and nuanced risk-benefit analyses. Efforts have been underway to clarify the ethics of using human challenges for novel pathogens and pathogens with pandemic potential, resulting in a framework for deciding when it is suitable to conduct human challenge trials and the necessary steps to ensure their ethical conduct (see @Williams2023Ethics). While ethical considerations are important, the direct health risks to trial participants are likely low (see e.g. @Manheim2021Exploring). 


# Conclusion

In conclusion, our epidemiological modelling suggests that accelerating COVID-19 vaccine approvals could result in significant health benefits, with potentially thousands of lives saved in just a few months. There are large uncertainties in the model, associated costs, and practical feasibility of any such innovations, especially human challenge trials. However, the potential benefits of faster vaccine availability are very large, especially considering the global public good nature of vaccines.

[^17]: In the period between 1 January and 1 July 2021 there were 61,000 confirmed COVID deaths in the UK and 246,000 in the US [@Mathieu2021Aglobal]).

[^18]: The assumption of 33% chance of success (i.e. probability of regulatory approval, conditional on positive results of Phase 1/2 trials—in case of COVID-19 around May 2020) may be a slightly conservative assumption for COVID, since the vaccine developers were optimistic of approval by the time Phase 2 trials started. However, it is higher than some of the historic probabilities of clinical trial success in vaccine development [@Gouglas2018Estimating].

[^19]: See @DBEI2021World. However, the cost of the HCT itself was likely closer to about £10 million [@Shares2020Open]. The purpose of this human challenge trial was to conduct a characterization study rather than a vaccine study. Its primary objective was to determine an optimal inoculum dose, while the secondary objective involved evaluating the kinetics of the virus and symptoms during the infection process [@Killingley2022Safety]. As an illustrative example, the rotavirus Rotarix vaccine Phase 3 trial costs are estimated to have cost between $136 million and $204 million [@Light2009Estimated].

[^20]: The World Health Organisation published eight criteria for the ethical use of SARS-CoV-2 challenge studies, which focused on scientific and ethical assessments, consultation and coordination, selection criteria, and review and consent (see @Jamrozik2021Key)
